pull_request_rules:
  - name: Enforce Two Code Owner Approvals
    conditions:
      - "base=main"
      - "status-success=continuous-integration"
      - "#approved-reviews-by>=2"
      - "current-review-requested-reviewer!=None"
      - "author!=bot"
      - "not closed"
      - "not merged"
    actions:
      merge:
        method: merge
        strict: smart

  - name: Require Two Code Owner Approvals
    conditions:
      - "base=main"
      - "author!=bot"
      - "not closed"
      - "not merged"
      - or:
          - "approved-reviews-by~=my-org-tech-decipher/team-1 AND #approved-reviews-by-by-team>=2"
          - "approved-reviews-by~=my-org-tech-decipher/team-2 AND #approved-reviews-by-by-team>=2"
    actions:
      comment:
        message: "This PR requires two approvals from code owners (team-1 or team-2)."
