pull_request_rules:
  - name: Enforce Two Code Owner Approvals
    conditions:
      - "base=main"
      - "status-success=continuous-integration"
      - "#approved-reviews-by>=2"
      - "author!=bot"
      - "state=open"
      - "merged=false"
    actions:
      merge:
        method: merge
        strict: false

  - name: Require Two Code Owner Approvals
    conditions:
      - "base=main"
      - "author!=bot"
      - "state=open"
      - "merged=false"
      - "approved-reviews-by~=my-org-tech-decipher/team-1"
      - "approved-reviews-by~=my-org-tech-decipher/team-2"
    actions:
      comment:
        message: "This PR requires approvals from both team-1 and team-2 members."
